spring:
  profiles:
    active: @spring.profiles.active@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update           # Use 'update', 'validate', 'create', or 'create-drop' as per your needs
    show-sql: true               # Set to true to log SQL queries
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      springframework:
        web: DEBUG               # Optional: Enables detailed logs for debugging web requests

# Enable Web Exposure Actuator Endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always